### ISSUE TITLE
Error at launch

### ISSUE THREAD

**Issue by VLEFF** [LucBerge/B4D#25]
Hello,
I have an Exception when i try to start the application:

java -jar B4D-2019.11.09.jar

 =>

Exception in thread "main" java.lang.UnsatisfiedLinkError: C:\Users\myuser\AppData\Local\Temp\jna-2095686\jna10876926830729102268.dll: Can't find dependent libraries
        at java.base/java.lang.ClassLoader$NativeLibrary.load0(Native Method)
        at java.base/java.lang.ClassLoader$NativeLibrary.load(ClassLoader.java:2430)
        at java.base/java.lang.ClassLoader$NativeLibrary.loadLibrary(ClassLoader.java:2487)
        at java.base/java.lang.ClassLoader.loadLibrary0(ClassLoader.java:2684)
        at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2617)
        at java.base/java.lang.Runtime.load0(Runtime.java:765)
        at java.base/java.lang.System.load(System.java:1835)
        at com.sun.jna.Native.loadNativeDispatchLibraryFromClasspath(Native.java:851)
        at com.sun.jna.Native.loadNativeDispatchLibrary(Native.java:826)
        at com.sun.jna.Native.<clinit>(Native.java:140)
        at com.sun.jna.Pointer.<clinit>(Pointer.java:41)
        at com.sun.jna.ptr.PointerByReference.<init>(PointerByReference.java:28)
        at com.sun.jna.ptr.PointerByReference.<init>(PointerByReference.java:24)
        at org.pcap4j.core.Pcaps.findAllDevs(Pcaps.java:51)
        at org.pcap4j.core.Pcaps.getDevByAddress(Pcaps.java:99)
        at fr.B4D.socket.PcapsFinder.findActiveDevice(PcapsFinder.java:45)
        at fr.B4D.socket.SocketListener.<init>(SocketListener.java:56)
        at fr.B4D.bot.B4D.<init>(B4D.java:67)
        at fr.B4D.gui.JFrame_B4D.<init>(JFrame_B4D.java:62)
        at fr.B4D.gui.JFrame_B4D.main(JFrame_B4D.java:53)

**Comment by LucBerge** [comment]
Hi ! First, thanks for the bug report. Before going any further, you have to keep in mind that this program is under development. The (OLD) pre-release (11.09.2019) you are using is outdated because of more recent Dofus updates. Nothing will work except the GUI. A lot of work need to be done and if you are a java developer, you can help us ! 😄 

About your bug :
Are you running it on windows ?

**Comment by VLEFF** [comment]
Yes, i'm running it on windows, and I have Java11 and npCap installed (also tried with winCap, same result)
Actually I was only looking for an already working deserializer for the data sniffed.
I just tried to launch the app with the executable for the sake of trying it... If you say it's depecrecated, no need to fix it I guess.
 I'll try tomorrow from the sources directly, and give you the update here

**Comment by LucBerge** [comment]
The `dev` branch hoever is up to date. If you need a working parser for the data sniffing, you can check [this file](https://github.com/LucBerge/B4D/blob/dev/src/main/java/fr/B4D/socket/SocketType.java). Each constant has a socket id and a Parser. You can then check the parser to see how to...parse. Wouldn't it be nice to have a wiki (or any other plateform) where people can share what they know about the current socket format ? I can help you and you can help me on it.
