### ISSUE TITLE
Erorr

### ISSUE THREAD

**Issue by RandoomV** [LucBerge/B4D#8]
PacketCapture: loading native library jpcap.. ok
fr.B4D.bot.B4DException: Merci de vйrifier votre connection internet.
        at fr.B4D.socket.os.Windows.findActiveDevice(Windows.java:47)
        at fr.B4D.socket.SocketListener.<init>(SocketListener.java:61)
        at fr.B4D.bot.B4D.<init>(B4D.java:74)
        at fr.B4D.gui.JFrame_B4D.<init>(JFrame_B4D.java:64)
        at fr.B4D.gui.JFrame_B4D.main(JFrame_B4D.java:55)

**Comment by LucBerge** [comment]
Cette erreur ne devrait plus se reproduire avec la [dernière version](https://github.com/LucBerge/B4D/releases/latest). Plus besoin de java 32 bits ou de quelconque librairie. La [nouvelle installation](https://github.com/LucBerge/B4D/wiki/Installer) est bien plus simple.
